<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <InvariantGlobalization>false</InvariantGlobalization>
    <UserSecretsId>axpense-api</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Axpense.Core\Axpense.Core.csproj" />
    <ProjectReference Include="..\Axpense.Infrastructure\Axpense.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>
</Project>
