export type Market = {
  code: string;
  slug: string;
  nameEn: string;
  nameAr: string;
  en: { h1: string; intro: string; focus: string[]; faq: { q: string; a: string }[] };
  ar: { h1: string; intro: string; focus: string[]; faq: { q: string; a: string }[] };
};

export const MARKETS: Market[] = [
  {
    code: 'eg', slug: 'egypt', nameEn: 'Egypt', nameAr: 'مصر',
    en: { h1: 'Fleet Management Software in Egypt for Vehicles, Maintenance and Operating Costs', intro: 'Axpense helps Egyptian businesses manage vehicles, fleet maintenance, fuel, expenses, inspections and assets from one operational platform.', focus: ['Fleet management for logistics, transportation, construction, manufacturing and other businesses that operate vehicles or physical assets.', 'Fleet maintenance and preventive maintenance records that keep scheduled work visible to operations teams.', 'Vehicle, fuel and expense records connected to the asset they belong to.', 'Asset and equipment records for teams that manage more than vehicles.', 'Reports and operational data that replace manual consolidation across spreadsheets.'], faq: [{q:'What can Axpense manage in Egypt?',a:'Axpense can centralize vehicles, drivers, maintenance, work orders, inspections, fuel, expenses, assets and operational reporting.'},{q:'Is Axpense only for transportation companies?',a:'No. The platform is relevant to any business that manages vehicles, equipment or physical assets, including logistics, construction, manufacturing, real estate and other operations.'}] },
    ar: { h1: 'برنامج إدارة الأسطول في مصر للمركبات والصيانة والتكاليف', intro: 'يساعد أكسبنس الشركات في مصر على إدارة المركبات وصيانة الأسطول والوقود والمصروفات والفحوصات والأصول من منصة تشغيلية واحدة.', focus: ['إدارة الأسطول للشركات التي تدير مركبات أو أصولًا مادية في قطاعات مثل اللوجستيات والنقل والإنشاءات والتصنيع.', 'إدارة الصيانة والصيانة الوقائية مع إبقاء الأعمال المجدولة واضحة لفريق التشغيل.', 'ربط بيانات المركبات والوقود والمصروفات بالأصل الذي تخصه.', 'إدارة الأصول والمعدات للشركات التي تتعامل مع أكثر من المركبات.', 'تقارير تشغيلية تقلل الاعتماد على تجميع البيانات يدويًا في جداول إكسل.'], faq: [{q:'ماذا يمكن لأكسبنس إدارته في مصر؟',a:'يمكن لأكسبنس تجميع بيانات المركبات والسائقين والصيانة وأوامر الشغل والفحوصات والوقود والمصروفات والأصول والتقارير التشغيلية.'},{q:'هل أكسبنس مخصص لشركات النقل فقط؟',a:'لا. المنصة مناسبة للشركات التي تدير مركبات أو معدات أو أصولًا مادية، ومنها اللوجستيات والإنشاءات والتصنيع والعقارات وغيرها.'}] }
  },
  {
    code:'sa', slug:'saudi-arabia', nameEn:'Saudi Arabia', nameAr:'السعودية',
    en:{h1:'Fleet Management Software in Saudi Arabia for Growing Operations',intro:'Manage vehicles, maintenance, fuel, expenses, inspections and physical assets with Axpense for operations in Saudi Arabia.',focus:['Fleet records and driver assignments for distributed operational teams.','Preventive maintenance and work orders for vehicles that need planned service.','Fuel and expense records connected to individual vehicles and assets.','Equipment and asset management alongside vehicle operations.','Operational reports for reviewing maintenance activity and fleet costs.'],faq:[{q:'Can Axpense manage both vehicles and equipment?',a:'Yes. Axpense is designed to centralize vehicle, fleet, equipment and asset records with maintenance and cost information.'},{q:'Can Saudi businesses use Axpense for maintenance management?',a:'Yes. The maintenance workflows cover scheduled maintenance, work orders and service history.'}]},
    ar:{h1:'برنامج إدارة الأسطول في السعودية للمركبات والصيانة والتكاليف',intro:'إدارة المركبات والصيانة والوقود والمصروفات والفحوصات والأصول باستخدام أكسبنس للشركات في السعودية.',focus:['سجلات الأسطول وتعيين السائقين لفرق التشغيل المختلفة.','الصيانة الوقائية وأوامر الشغل للمركبات التي تحتاج إلى صيانة مخططة.','ربط بيانات الوقود والمصروفات بكل مركبة أو أصل.','إدارة المعدات والأصول بجانب تشغيل المركبات.','تقارير تشغيلية لمراجعة الصيانة وتكاليف الأسطول.'],faq:[{q:'هل يمكن لأكسبنس إدارة المركبات والمعدات معًا؟',a:'نعم. يجمع أكسبنس سجلات المركبات والأسطول والمعدات والأصول مع بيانات الصيانة والتكاليف.'},{q:'هل يمكن استخدام أكسبنس لإدارة صيانة الأسطول في السعودية؟',a:'نعم. تشمل المنصة الصيانة المجدولة وأوامر الشغل وسجل الصيانة.'}]}
  },
  {
    code:'ae',slug:'united-arab-emirates',nameEn:'United Arab Emirates',nameAr:'الإمارات العربية المتحدة',
    en:{h1:'Fleet Management Software in the UAE for Vehicles, Assets and Maintenance',intro:'Axpense gives UAE businesses one place to manage fleet operations, maintenance, fuel, expenses, inspections and assets.',focus:['Centralized vehicle and asset records for operational teams.','Maintenance scheduling and work order visibility for planned and corrective work.','Fuel and operating expenses linked to the relevant vehicle.','Equipment and asset records for businesses with mixed physical assets.','Reports that connect operational activity with cost information.'],faq:[{q:'What does Axpense cover for UAE fleet operations?',a:'Vehicle records, driver assignments, maintenance, work orders, inspections, fuel, expenses, assets and reports are all part of the platform.'},{q:'Can Axpense support mixed fleets and equipment?',a:'Yes. The product is positioned for organizations managing vehicles alongside equipment and other physical assets.'}]},
    ar:{h1:'برنامج إدارة الأسطول في الإمارات للمركبات والأصول والصيانة',intro:'يوفر أكسبنس للشركات في الإمارات مكانًا واحدًا لإدارة الأسطول والصيانة والوقود والمصروفات والفحوصات والأصول.',focus:['سجلات موحدة للمركبات والأصول لفريق التشغيل.','جدولة الصيانة ومتابعة أوامر الشغل للأعمال المخططة والإصلاحات.','ربط الوقود والمصروفات بالمركبة المعنية.','إدارة المعدات والأصول للشركات ذات الأصول المتنوعة.','تقارير تربط النشاط التشغيلي بالتكاليف.'],faq:[{q:'ماذا يغطي أكسبنس لإدارة الأسطول في الإمارات؟',a:'تشمل المنصة سجلات المركبات وتعيين السائقين والصيانة وأوامر الشغل والفحوصات والوقود والمصروفات والأصول والتقارير.'},{q:'هل يدعم أكسبنس المركبات والمعدات معًا؟',a:'نعم. يمكن إدارة المركبات والمعدات والأصول المادية ضمن نفس المنصة.'}]}
  },
  {
    code:'qa',slug:'qatar',nameEn:'Qatar',nameAr:'قطر',
    en:{h1:'Fleet Management Software in Qatar for Vehicles and Equipment',intro:'Centralize fleet maintenance, fuel, expenses, inspections and equipment records with Axpense for businesses in Qatar.',focus:['Vehicle and driver records for operational visibility.','Planned maintenance and work orders for service vehicles and equipment.','Fuel and expense tracking by vehicle or asset.','Inspection records and maintenance issues in one operational history.','Reports for maintenance and fleet cost review.'],faq:[{q:'Is Axpense suitable for businesses managing equipment in Qatar?',a:'Yes. Axpense covers equipment and asset records alongside vehicle and fleet workflows.'},{q:'Can maintenance and expenses be connected?',a:'Yes. Maintenance work and operating expenses can be kept in the context of the relevant vehicle or asset.'}]},
    ar:{h1:'برنامج إدارة الأسطول في قطر للمركبات والمعدات',intro:'تجميع إدارة صيانة الأسطول والوقود والمصروفات والفحوصات وسجلات المعدات باستخدام أكسبنس للشركات في قطر.',focus:['سجلات المركبات والسائقين لزيادة وضوح التشغيل.','الصيانة المخططة وأوامر الشغل للمركبات والمعدات.','تتبع الوقود والمصروفات حسب المركبة أو الأصل.','سجلات الفحوصات ومشكلات الصيانة ضمن سجل تشغيلي واحد.','تقارير لمراجعة الصيانة وتكاليف الأسطول.'],faq:[{q:'هل يناسب أكسبنس الشركات التي تدير معدات في قطر؟',a:'نعم. يغطي أكسبنس سجلات المعدات والأصول بجانب إدارة المركبات والأسطول.'},{q:'هل يمكن ربط الصيانة بالمصروفات؟',a:'نعم. يمكن الاحتفاظ بأعمال الصيانة والمصروفات ضمن سجل المركبة أو الأصل المعني.'}]}
  },
  {
    code:'jo',slug:'jordan',nameEn:'Jordan',nameAr:'الأردن',
    en:{h1:'Fleet Management Software in Jordan for Vehicle and Asset Operations',intro:'Manage fleet records, preventive maintenance, fuel, expenses, inspections and assets with Axpense for businesses in Jordan.',focus:['Vehicle and driver records in one searchable system.','Preventive maintenance schedules and work orders.','Fuel and operating expense tracking by vehicle.','Inspection and issue records for operational follow-up.','Asset and equipment management for non-vehicle assets.'],faq:[{q:'What types of businesses can use Axpense in Jordan?',a:'Any organization managing vehicles, equipment or physical assets can evaluate Axpense, including logistics, transportation, construction, manufacturing and service operations.'},{q:'Does Axpense replace spreadsheet-based fleet records?',a:'It is designed to centralize the records and workflows that teams often keep across separate spreadsheets and files.'}]},
    ar:{h1:'برنامج إدارة الأسطول في الأردن للمركبات والأصول',intro:'إدارة سجلات الأسطول والصيانة الوقائية والوقود والمصروفات والفحوصات والأصول باستخدام أكسبنس للشركات في الأردن.',focus:['سجلات المركبات والسائقين في نظام واحد قابل للبحث.','جداول الصيانة الوقائية وأوامر الشغل.','تتبع الوقود ومصروفات التشغيل حسب المركبة.','سجلات الفحوصات والمشكلات للمتابعة التشغيلية.','إدارة الأصول والمعدات غير المرتبطة بالمركبات.'],faq:[{q:'ما أنواع الشركات التي يمكنها استخدام أكسبنس في الأردن؟',a:'يمكن لأي مؤسسة تدير مركبات أو معدات أو أصولًا مادية تقييم أكسبنس، ومنها اللوجستيات والنقل والإنشاءات والتصنيع والخدمات.'},{q:'هل يمكن لأكسبنس تقليل الاعتماد على جداول إكسل؟',a:'تم تصميمه لتجميع السجلات وسير العمل التي قد تكون موزعة بين جداول وملفات منفصلة.'}]}
  },
  {
    code:'iq',slug:'iraq',nameEn:'Iraq',nameAr:'العراق',
    en:{h1:'Fleet Management Software in Iraq for Vehicles, Equipment and Maintenance',intro:'Axpense centralizes vehicle, equipment, maintenance, fuel, expense and inspection records for businesses operating in Iraq.',focus:['Vehicle and asset records for field and operational teams.','Maintenance schedules and work orders for vehicles and equipment.','Fuel and expense records connected to assets.','Inspection and issue tracking for operational follow-up.','Reports that help teams review maintenance and operating costs.'],faq:[{q:'Can Axpense manage vehicles and equipment together in Iraq?',a:'Yes. The product supports vehicle, equipment and general asset records in the same operational model.'},{q:'Does Axpense include preventive maintenance?',a:'Yes. Preventive maintenance is a core workflow alongside work orders and maintenance history.'}]},
    ar:{h1:'برنامج إدارة الأسطول في العراق للمركبات والمعدات والصيانة',intro:'يجمع أكسبنس سجلات المركبات والمعدات والصيانة والوقود والمصروفات والفحوصات للشركات العاملة في العراق.',focus:['سجلات المركبات والأصول لفرق التشغيل والعمل الميداني.','جداول الصيانة وأوامر الشغل للمركبات والمعدات.','ربط الوقود والمصروفات بالأصول.','متابعة الفحوصات والمشكلات التشغيلية.','تقارير لمراجعة الصيانة وتكاليف التشغيل.'],faq:[{q:'هل يمكن لأكسبنس إدارة المركبات والمعدات معًا في العراق؟',a:'نعم. يدعم المنتج سجلات المركبات والمعدات والأصول ضمن نموذج تشغيلي واحد.'},{q:'هل يشمل أكسبنس الصيانة الوقائية؟',a:'نعم. الصيانة الوقائية جزء أساسي بجانب أوامر الشغل وسجل الصيانة.'}]}
  },
  {
    code:'mena',slug:'mena',nameEn:'MENA',nameAr:'منطقة الشرق الأوسط وشمال أفريقيا',
    en:{h1:'Fleet & Asset Management Software for MENA Businesses',intro:'Axpense provides a regional-ready structure for businesses managing vehicles, equipment, maintenance, fuel, expenses and physical assets across MENA.',focus:['One product structure for fleet, vehicle, asset and equipment records.','Maintenance, work orders and inspections connected to operational assets.','Fuel and expense tracking for clearer operating cost visibility.','Reports and analytics built around operational data.','Users and roles so regional, site and workshop teams each see what they need.'],faq:[{q:'Can one Axpense account cover operations in several countries?',a:'Yes. Vehicles, equipment and sites in different locations can be managed from the same Axpense account, with users and roles controlling who sees and edits what.'},{q:'Is Axpense available in Arabic?',a:'The Axpense website is available in English and Arabic. Contact the team to discuss language and localization needs for your users.'}]},
    ar:{h1:'برنامج إدارة الأسطول والأصول للشركات في منطقة الشرق الأوسط وشمال أفريقيا',intro:'يوفر أكسبنس بنية مناسبة للشركات التي تدير المركبات والمعدات والصيانة والوقود والمصروفات والأصول المادية في منطقة MENA.',focus:['هيكل موحد لإدارة الأسطول والمركبات والأصول والمعدات.','ربط الصيانة وأوامر الشغل والفحوصات بالأصول التشغيلية.','تتبع الوقود والمصروفات لتحسين وضوح تكاليف التشغيل.','تقارير وتحليلات مبنية على البيانات التشغيلية.','صلاحيات المستخدمين والأدوار ليرى كل فريق إقليمي أو موقع أو ورشة ما يحتاجه.'],faq:[{q:'هل يمكن إدارة عمليات في أكثر من دولة من حساب واحد؟',a:'نعم. يمكن إدارة المركبات والمعدات والمواقع المختلفة من نفس حساب أكسبنس، مع صلاحيات المستخدمين والأدوار للتحكم في من يرى ومن يعدّل.'},{q:'هل أكسبنس متاح باللغة العربية؟',a:'موقع أكسبنس متاح بالعربية والإنجليزية. تواصل مع الفريق لمناقشة احتياجات اللغة لمستخدميك.'}]}
  },
];

export function getMarket(code: string) { return MARKETS.find((m) => m.code === code); }
